openapi: 3.0.3
info:
  title: 'Heartpace Basic E-signature API Documentation'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/login:
    post:
      summary: Login
      operationId: login
      description: ''
      parameters: []
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  token: 5|L5iNL6oVTXdBfEiIo7n8mE5yKQVngBlYD3eTSZ4xc9dd8b3b
                properties:
                  token:
                    type: string
                    example: 5|L5iNL6oVTXdBfEiIo7n8mE5yKQVngBlYD3eTSZ4xc9dd8b3b
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The provided credentials do not match our records.'
                properties:
                  message:
                    type: string
                    example: 'The provided credentials do not match our records.'
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The password field is required.'
                  errors:
                    password: []
                properties:
                  message:
                    type: string
                    example: 'The password field is required.'
                  errors:
                    type: object
                    properties:
                      password:
                        type: array
                        example: []
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: lhayes@example.org
                password:
                  type: string
                  description: ''
                  example: dolorum
              required:
                - email
                - password
      security: []
  /api/register:
    post:
      summary: Register
      operationId: register
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 1
                    name: 'Dell Balistreri'
                    email: mcglynn.vilma@example.org
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: 'Dell Balistreri'
                      email:
                        type: string
                        example: mcglynn.vilma@example.org
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: qui
                email:
                  type: string
                  description: ''
                  example: trevor71@example.com
                password:
                  type: string
                  description: ''
                  example: "'k4sp_cWp4$E7"
                password_confirmation:
                  type: string
                  description: ''
                  example: tenetur
              required:
                - name
                - email
                - password
                - password_confirmation
      security: []
  /api/documents:
    get:
      summary: 'Get documents'
      operationId: getDocuments
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      filename: faker9ZBJaf
                      signature_status: Signed
                      signed_by: null
                      signed_at: null
                    -
                      id: 2
                      filename: fakerqQZUAF
                      signature_status: 'Not necessary'
                      signed_by: null
                      signed_at: null
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        filename: faker9ZBJaf
                        signature_status: Signed
                        signed_by: null
                        signed_at: null
                      -
                        id: 2
                        filename: fakerqQZUAF
                        signature_status: 'Not necessary'
                        signed_by: null
                        signed_at: null
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        filename:
                          type: string
                          example: faker9ZBJaf
                        signature_status:
                          type: string
                          example: Signed
                        signed_by:
                          type: string
                          example: null
                        signed_at:
                          type: string
                          example: null
      tags:
        - Documents
    post:
      summary: 'Upload a document'
      operationId: uploadADocument
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 3
                    filename: fakerulIV1F
                    signature_status: Signed
                    signed_by: null
                    signed_at: null
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 3
                      filename:
                        type: string
                        example: fakerulIV1F
                      signature_status:
                        type: string
                        example: Signed
                      signed_by:
                        type: string
                        example: null
                      signed_at:
                        type: string
                        example: null
      tags:
        - Documents
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                document:
                  type: string
                  format: binary
                  description: 'Must be a file.'
              required:
                - document
  '/api/documents/{id}':
    get:
      summary: 'Download a document'
      operationId: downloadADocument
      description: 'Download a document uploaded or signed by the user.'
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Documents
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the document.'
        example: 4
        required: true
        schema:
          type: integer
  /api/sign-document:
    post:
      summary: 'Sign a document'
      operationId: signADocument
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 9
                    filename: fakerUDGsfx
                    signature_status: 'Not necessary'
                    signed_by: null
                    signed_at: null
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 9
                      filename:
                        type: string
                        example: fakerUDGsfx
                      signature_status:
                        type: string
                        example: 'Not necessary'
                      signed_by:
                        type: string
                        example: null
                      signed_at:
                        type: string
                        example: null
      tags:
        - 'Sign a document'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                request_id:
                  type: integer
                  description: ''
                  example: 11
                signature:
                  type: string
                  format: binary
                  description: 'Must be a file.'
              required:
                - request_id
                - signature
  /api/signature-requests/received-requests:
    get:
      summary: 'Get received requests'
      operationId: getReceivedRequests
      description: 'Return the list of signature requests received by the authorized user.'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      document:
                        id: 4
                        filename: fakerx7xjJj
                        signature_status: 'Not necessary'
                        signed_by: null
                        signed_at: null
                      requested_by:
                        id: 6
                        name: 'Johnson Emard'
                        email: green.icie@example.net
                      requested_from:
                        id: 7
                        name: 'Mr. Angus Senger I'
                        email: waino.labadie@example.com
                      deadline: '2024-09-09T17:48:31.000000Z'
                      signature_positions:
                        -
                          X: 50
                          'Y': 50
                          page: 1
                      requested_at: '2024-09-08T17:48:31.000000Z'
                      status: Pending
                    -
                      id: 2
                      document:
                        id: 5
                        filename: fakerBKRWki
                        signature_status: 'Not necessary'
                        signed_by: null
                        signed_at: null
                      requested_by:
                        id: 9
                        name: 'Mabel Wolff III'
                        email: mertz.ayla@example.org
                      requested_from:
                        id: 10
                        name: 'Nels Jacobs'
                        email: jailyn.bins@example.org
                      deadline: '2024-09-09T17:48:31.000000Z'
                      signature_positions:
                        -
                          X: 50
                          'Y': 50
                          page: 1
                      requested_at: '2024-09-08T17:48:31.000000Z'
                      status: Signed
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        document:
                          id: 4
                          filename: fakerx7xjJj
                          signature_status: 'Not necessary'
                          signed_by: null
                          signed_at: null
                        requested_by:
                          id: 6
                          name: 'Johnson Emard'
                          email: green.icie@example.net
                        requested_from:
                          id: 7
                          name: 'Mr. Angus Senger I'
                          email: waino.labadie@example.com
                        deadline: '2024-09-09T17:48:31.000000Z'
                        signature_positions:
                          -
                            X: 50
                            'Y': 50
                            page: 1
                        requested_at: '2024-09-08T17:48:31.000000Z'
                        status: Pending
                      -
                        id: 2
                        document:
                          id: 5
                          filename: fakerBKRWki
                          signature_status: 'Not necessary'
                          signed_by: null
                          signed_at: null
                        requested_by:
                          id: 9
                          name: 'Mabel Wolff III'
                          email: mertz.ayla@example.org
                        requested_from:
                          id: 10
                          name: 'Nels Jacobs'
                          email: jailyn.bins@example.org
                        deadline: '2024-09-09T17:48:31.000000Z'
                        signature_positions:
                          -
                            X: 50
                            'Y': 50
                            page: 1
                        requested_at: '2024-09-08T17:48:31.000000Z'
                        status: Signed
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        document:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 4
                            filename:
                              type: string
                              example: fakerx7xjJj
                            signature_status:
                              type: string
                              example: 'Not necessary'
                            signed_by:
                              type: string
                              example: null
                            signed_at:
                              type: string
                              example: null
                        requested_by:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 6
                            name:
                              type: string
                              example: 'Johnson Emard'
                            email:
                              type: string
                              example: green.icie@example.net
                        requested_from:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 7
                            name:
                              type: string
                              example: 'Mr. Angus Senger I'
                            email:
                              type: string
                              example: waino.labadie@example.com
                        deadline:
                          type: string
                          example: '2024-09-09T17:48:31.000000Z'
                        signature_positions:
                          type: array
                          example:
                            -
                              X: 50
                              'Y': 50
                              page: 1
                          items:
                            type: object
                            properties:
                              X:
                                type: integer
                                example: 50
                              'Y':
                                type: integer
                                example: 50
                              page:
                                type: integer
                                example: 1
                        requested_at:
                          type: string
                          example: '2024-09-08T17:48:31.000000Z'
                        status:
                          type: string
                          example: Pending
      tags:
        - 'Signature requests'
  /api/signature-requests:
    get:
      summary: 'Get made requests'
      operationId: getMadeRequests
      description: 'Returns the list of signature requests made by the authorized user.'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 3
                      document:
                        id: 6
                        filename: fakere6cqP8
                        signature_status: Pending
                        signed_by: null
                        signed_at: null
                      requested_by:
                        id: 12
                        name: 'Dr. Makayla Mertz MD'
                        email: quigley.cortez@example.com
                      requested_from:
                        id: 13
                        name: 'Mrs. Arielle Watsica PhD'
                        email: mstracke@example.org
                      deadline: '2024-09-09T17:48:31.000000Z'
                      signature_positions:
                        -
                          X: 50
                          'Y': 50
                          page: 1
                      requested_at: '2024-09-08T17:48:31.000000Z'
                      status: Signed
                    -
                      id: 4
                      document:
                        id: 7
                        filename: faker2Y8C46
                        signature_status: 'Not necessary'
                        signed_by: null
                        signed_at: null
                      requested_by:
                        id: 15
                        name: 'April Dicki'
                        email: jade.gibson@example.com
                      requested_from:
                        id: 16
                        name: 'Janick Conn'
                        email: ethan.beahan@example.org
                      deadline: '2024-09-09T17:48:31.000000Z'
                      signature_positions:
                        -
                          X: 50
                          'Y': 50
                          page: 1
                      requested_at: '2024-09-08T17:48:31.000000Z'
                      status: Signed
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 3
                        document:
                          id: 6
                          filename: fakere6cqP8
                          signature_status: Pending
                          signed_by: null
                          signed_at: null
                        requested_by:
                          id: 12
                          name: 'Dr. Makayla Mertz MD'
                          email: quigley.cortez@example.com
                        requested_from:
                          id: 13
                          name: 'Mrs. Arielle Watsica PhD'
                          email: mstracke@example.org
                        deadline: '2024-09-09T17:48:31.000000Z'
                        signature_positions:
                          -
                            X: 50
                            'Y': 50
                            page: 1
                        requested_at: '2024-09-08T17:48:31.000000Z'
                        status: Signed
                      -
                        id: 4
                        document:
                          id: 7
                          filename: faker2Y8C46
                          signature_status: 'Not necessary'
                          signed_by: null
                          signed_at: null
                        requested_by:
                          id: 15
                          name: 'April Dicki'
                          email: jade.gibson@example.com
                        requested_from:
                          id: 16
                          name: 'Janick Conn'
                          email: ethan.beahan@example.org
                        deadline: '2024-09-09T17:48:31.000000Z'
                        signature_positions:
                          -
                            X: 50
                            'Y': 50
                            page: 1
                        requested_at: '2024-09-08T17:48:31.000000Z'
                        status: Signed
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 3
                        document:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 6
                            filename:
                              type: string
                              example: fakere6cqP8
                            signature_status:
                              type: string
                              example: Pending
                            signed_by:
                              type: string
                              example: null
                            signed_at:
                              type: string
                              example: null
                        requested_by:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 12
                            name:
                              type: string
                              example: 'Dr. Makayla Mertz MD'
                            email:
                              type: string
                              example: quigley.cortez@example.com
                        requested_from:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 13
                            name:
                              type: string
                              example: 'Mrs. Arielle Watsica PhD'
                            email:
                              type: string
                              example: mstracke@example.org
                        deadline:
                          type: string
                          example: '2024-09-09T17:48:31.000000Z'
                        signature_positions:
                          type: array
                          example:
                            -
                              X: 50
                              'Y': 50
                              page: 1
                          items:
                            type: object
                            properties:
                              X:
                                type: integer
                                example: 50
                              'Y':
                                type: integer
                                example: 50
                              page:
                                type: integer
                                example: 1
                        requested_at:
                          type: string
                          example: '2024-09-08T17:48:31.000000Z'
                        status:
                          type: string
                          example: Signed
      tags:
        - 'Signature requests'
    post:
      summary: 'Create a request'
      operationId: createARequest
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 5
                    document:
                      id: 8
                      filename: fakerof2Ym7
                      signature_status: Signed
                      signed_by: null
                      signed_at: null
                    requested_by:
                      id: 18
                      name: 'Eden Moen'
                      email: goodwin.violette@example.net
                    requested_from:
                      id: 19
                      name: 'Micheal Terry'
                      email: gschumm@example.org
                    deadline: '2024-09-09T17:48:31.000000Z'
                    signature_positions:
                      -
                        X: 50
                        'Y': 50
                        page: 1
                    requested_at: '2024-09-08T17:48:31.000000Z'
                    status: Signed
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 5
                      document:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 8
                          filename:
                            type: string
                            example: fakerof2Ym7
                          signature_status:
                            type: string
                            example: Signed
                          signed_by:
                            type: string
                            example: null
                          signed_at:
                            type: string
                            example: null
                      requested_by:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 18
                          name:
                            type: string
                            example: 'Eden Moen'
                          email:
                            type: string
                            example: goodwin.violette@example.net
                      requested_from:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 19
                          name:
                            type: string
                            example: 'Micheal Terry'
                          email:
                            type: string
                            example: gschumm@example.org
                      deadline:
                        type: string
                        example: '2024-09-09T17:48:31.000000Z'
                      signature_positions:
                        type: array
                        example:
                          -
                            X: 50
                            'Y': 50
                            page: 1
                        items:
                          type: object
                          properties:
                            X:
                              type: integer
                              example: 50
                            'Y':
                              type: integer
                              example: 50
                            page:
                              type: integer
                              example: 1
                      requested_at:
                        type: string
                        example: '2024-09-08T17:48:31.000000Z'
                      status:
                        type: string
                        example: Signed
      tags:
        - 'Signature requests'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                document_id:
                  type: integer
                  description: ''
                  example: 17
                requested_from:
                  type: string
                  description: 'Must be a valid email address.'
                  example: chase.ernser@example.net
                signature_positions:
                  type: array
                  description: ''
                  example:
                    - []
                  items:
                    type: object
                    properties:
                      page:
                        type: integer
                        description: ''
                        example: 7
                      X:
                        type: integer
                        description: ''
                        example: 9
                      'Y':
                        type: integer
                        description: ''
                        example: 12
                    required:
                      - page
                      - X
                      - 'Y'
                deadline:
                  type: string
                  description: 'Must be a valid date in the format <code>Y-m-d\TH:i:sP</code>. Must be a date after or equal to <code>now</code>.'
                  example: '2046-09-29'
              required:
                - document_id
                - requested_from
                - signature_positions
                - deadline
tags:
  -
    name: Authentication
    description: ''
  -
    name: Documents
    description: ''
  -
    name: 'Sign a document'
    description: ''
  -
    name: 'Signature requests'
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by making a POST request to the login API endpoint with your email and password.'
security:
  -
    default: []
